CREATE DATABASE gdcheeriosdb;
\c gdcheeriosdb;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

DO
$$
    DECLARE
        monitor_user TEXT := current_setting('custom.monitor_user', true);
        monitor_pass TEXT := current_setting('custom.monitor_password', true);
    BEGIN
        IF monitor_user IS NOT NULL AND monitor_pass IS NOT NULL THEN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = monitor_user) THEN
                EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L', monitor_user, monitor_pass);
            ELSE
                EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', monitor_user, monitor_pass);
            END IF;

            EXECUTE format('GRANT pg_monitor TO %I', monitor_user);
            EXECUTE format('GRANT SELECT ON pg_stat_statements TO %I', monitor_user);
        END IF;
    END
$$;

-- ==========================================
-- 1. SCHEMA DEFINITIONS
-- ==========================================
CREATE SCHEMA IF NOT EXISTS account;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS gq;
CREATE SCHEMA IF NOT EXISTS osu;

-- ==========================================
-- 2. CUSTOM TYPES (ENUMS)
-- ==========================================
CREATE TYPE account.status AS ENUM (
    'user',
    'restricted',
    'test'
    );

CREATE TYPE api.key_status AS ENUM (
    'active',
    'revoked',
    'expired'
    );

CREATE TYPE gq.statistic_type AS ENUM (
    'heal',
    'player_damage',
    'enemy_damage',
    'kill',
    'death',
    'money_gained',
    'money_spent',
    'effect_add',
    'hit_enemy',
    'hit_player',
    'item_add',
    'item_remove'
    );


-- ==========================================
-- 3. ACCOUNT SCHEMA (Identity)
-- ==========================================
CREATE TABLE account.users
(
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        text                                                       NOT NULL,
    password        text                                                       NOT NULL,
    email           text                                                       NOT NULL,
    about           text,
    status          account.status              DEFAULT 'user'::account.status NOT NULL,
    created         timestamp without time zone DEFAULT now(),
    is_supporter    boolean                     DEFAULT false                  NOT NULL,
    last_support    timestamp with time zone,
    supporter_lasts timestamp with time zone,
    is_admin        boolean                     DEFAULT false                  NOT NULL
);

CREATE TABLE account.tags
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    title      text    NOT NULL,
    type       text    NOT NULL
);

CREATE TABLE account.supports
(
    id           uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id      integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    weeks        integer                  DEFAULT 1     NOT NULL,
    supported_on timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE account.pending
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text                                                            NOT NULL,
    email    text                                                            NOT NULL,
    about    text,
    password text                                                            NOT NULL,
    sent     timestamp with time zone DEFAULT now()                          NOT NULL,
    expires  timestamp with time zone DEFAULT (now() + '24:00:00'::interval) NOT NULL,
    token    text                                                            NOT NULL
);

CREATE TABLE account.sessions
(
    id         uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id    integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE account.password_resets
(
    id         uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id    integer                                                         NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval) NOT NULL
);

-- ==========================================
-- 4. AUTH SCHEMA (Security & Access)
-- ==========================================
CREATE TABLE auth.identities
(
    id               uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id          integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    provider         text                                   NOT NULL,
    provider_subject text                                   NOT NULL,
    created_at       timestamp with time zone DEFAULT now() NOT NULL
);

-- ==========================================
-- 5. API SCHEMA (System Keys & Logging)
-- ==========================================
CREATE TABLE api.keys
(
    id                       uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    key_id                   text UNIQUE                                               NOT NULL,
    secret_hash              text                                                      NOT NULL,
    name                     text,
    scopes                   jsonb                    DEFAULT '[]'::jsonb              NOT NULL,
    created_at               timestamp with time zone DEFAULT now()                    NOT NULL,
    last_used_at             timestamp with time zone,
    expires_at               timestamp with time zone,
    status                   api.key_status           DEFAULT 'active'::api.key_status NOT NULL,
    created_by_ip            inet,
    last_used_ip             inet,
    metadata                 jsonb,
    user_id                  integer REFERENCES account.users (id) ON DELETE CASCADE,
    refresh_token_hash       text,
    refresh_token_expires_at timestamp with time zone,
    last_refreshed_at        timestamp with time zone,
    rotated_from_key_id      text
);

CREATE INDEX idx_api_keys_last_used_at ON api.keys USING btree (last_used_at);
CREATE INDEX idx_api_keys_status ON api.keys USING btree (status);

-- ==========================================
-- 6. GQ SCHEMA (Gentry's Quest)
-- ==========================================
CREATE TABLE gq.profiles
(
    account_id integer PRIMARY KEY REFERENCES account.users (id) ON DELETE CASCADE,
    money      bigint   DEFAULT 0                NOT NULL,
    weighted   smallint DEFAULT 0                NOT NULL,
    unweighted integer  DEFAULT 0                NOT NULL,
    rank       text     DEFAULT 'unranked'::text NOT NULL,
    tier       smallint DEFAULT 0                NOT NULL
);

CREATE TABLE gq.items
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata jsonb                                 NOT NULL,
    rating   integer                     DEFAULT 0 NOT NULL,
    owner_id integer REFERENCES account.users (id) ON DELETE CASCADE,
    is_new   boolean                     DEFAULT false,
    obtained timestamp without time zone DEFAULT now()
);

CREATE TABLE gq.leaderboards
(
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   text    NOT NULL,
    online boolean NOT NULL
);

CREATE TABLE gq.visitations
(
    id       uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id  integer REFERENCES account.users (id) ON DELETE CASCADE,
    location text,
    arrived  timestamp with time zone DEFAULT now() NOT NULL,
    departed timestamp with time zone
);

CREATE TABLE gq.scores
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text                                   NOT NULL,
    score          bigint                                 NOT NULL,
    leaderboard_id integer                                NOT NULL REFERENCES gq.leaderboards (id) ON DELETE CASCADE,
    user_id        integer REFERENCES account.users (id) ON DELETE CASCADE,
    submitted_at   timestamp with time zone DEFAULT now() NOT NULL,
    visitation_id  uuid                                   REFERENCES gq.visitations (id) ON DELETE SET NULL
);

CREATE TABLE gq.statistics
(
    id             uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id        integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    type           gq.statistic_type                      NOT NULL,
    amount         integer                  DEFAULT 0     NOT NULL,
    enemy          text                     DEFAULT null,
    character      text                     DEFAULT null,
    weapon         text                     DEFAULT null,
    location       text                     DEFAULT null,
    status_effect  text                     DEFAULT null,
    visitation_id  uuid                                   REFERENCES gq.visitations (id) ON DELETE SET NULL,
    leaderboard_id integer                                REFERENCES gq.leaderboards (id) ON DELETE SET NULL,
    happened       timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_gq_stats_user ON gq.statistics USING btree (user_id);

CREATE TABLE gq.metrics
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer REFERENCES account.users (id) ON DELETE CASCADE,
    recorded_at date    DEFAULT now() NOT NULL,
    rank        integer DEFAULT 0     NOT NULL,
    gp          integer DEFAULT 0     NOT NULL
);

-- ==========================================
-- 7. OSU SCHEMA (Osu! Tracking)
-- ==========================================
CREATE TABLE osu.users
(
    id           bigint PRIMARY KEY,
    username     text,
    score        bigint                   DEFAULT 0                                                                                                            NOT NULL,
    playcount    integer                  DEFAULT 0                                                                                                            NOT NULL,
    accuracy     numeric(5, 2)            DEFAULT 0                                                                                                            NOT NULL,
    performance  integer                  DEFAULT 0                                                                                                            NOT NULL,
    rank         integer                  DEFAULT 0                                                                                                            NOT NULL,
    last_refresh timestamp with time zone DEFAULT now()                                                                                                        NOT NULL,
    avatar       text                     DEFAULT 'https://a.ppy.sh/1'::text                                                                                   NOT NULL,
    background   text                     DEFAULT 'https://c4.wallpaperflare.com/wallpaper/39/35/772/osu-games-art-digital-art-hd-wallpaper-preview.jpg'::text NOT NULL
);

CREATE TABLE osu.matches
(
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text,
    open      boolean                  DEFAULT true  NOT NULL,
    pinned    boolean                  DEFAULT false NOT NULL,
    ended     boolean                  DEFAULT false NOT NULL,
    started   timestamp with time zone DEFAULT now() NOT NULL,
    opener_id integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE
);

CREATE TABLE osu.match_users
(
    match_id           integer REFERENCES osu.matches (id) ON DELETE CASCADE,
    user_id            bigint REFERENCES osu.users (id) ON DELETE CASCADE,
    starting_score     bigint DEFAULT 0 NOT NULL,
    starting_playcount bigint DEFAULT 0 NOT NULL,
    nickname           text,
    ending_score       bigint,
    ending_playcount   bigint,
    team               text,
    PRIMARY KEY (match_id, user_id)
);
