CREATE DATABASE gdcheeriosdb;
\c gdcheeriosdb;

CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

DO
$$
    DECLARE
        monitor_user TEXT := current_setting('custom.monitor_user', true);
        monitor_pass TEXT := current_setting('custom.monitor_password', true);
    BEGIN
        IF monitor_user IS NOT NULL AND monitor_pass IS NOT NULL THEN
            IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = monitor_user) THEN
                EXECUTE format('CREATE ROLE %I WITH LOGIN PASSWORD %L', monitor_user, monitor_pass);
            ELSE
                EXECUTE format('ALTER ROLE %I WITH PASSWORD %L', monitor_user, monitor_pass);
            END IF;

            EXECUTE format('GRANT pg_monitor TO %I', monitor_user);
            EXECUTE format('GRANT SELECT ON pg_stat_statements TO %I', monitor_user);
        END IF;
    END
$$;

-- ==========================================
-- 1. SCHEMA DEFINITIONS
-- ==========================================
CREATE SCHEMA IF NOT EXISTS account;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS gq;
CREATE SCHEMA IF NOT EXISTS osu;

-- ==========================================
-- 2. CUSTOM TYPES (ENUMS)
-- ==========================================
CREATE TYPE account.status AS ENUM (
    'user',
    'restricted',
    'test'
    );

CREATE TYPE api.key_status AS ENUM (
    'active',
    'revoked',
    'expired'
    );

CREATE TYPE gq.statistic_type AS ENUM (
    'heal',
    'player_damage',
    'enemy_damage',
    'kill',
    'death',
    'money_gained',
    'money_spent',
    'effect_add',
    'hit_enemy',
    'hit_player',
    'item_add',
    'item_remove'
    );


-- ==========================================
-- 3. ACCOUNT SCHEMA (Identity)
-- ==========================================
CREATE TABLE account.users
(
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        text                                                       NOT NULL,
    password        text                                                       NOT NULL,
    email           text                                                       NOT NULL,
    about           text,
    status          account.status              DEFAULT 'user'::account.status NOT NULL,
    created         timestamp without time zone DEFAULT now(),
    is_supporter    boolean                     DEFAULT false                  NOT NULL,
    last_support    timestamp with time zone,
    supporter_lasts timestamp with time zone,
    is_admin        boolean                     DEFAULT false                  NOT NULL
);

CREATE TABLE account.tags
(
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    title      text    NOT NULL,
    type       text    NOT NULL
);

CREATE TABLE account.supports
(
    id           uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id      integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    weeks        integer                  DEFAULT 1     NOT NULL,
    supported_on timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE account.pending
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text                                                            NOT NULL,
    email    text                                                            NOT NULL,
    about    text,
    password text                                                            NOT NULL,
    sent     timestamp with time zone DEFAULT now()                          NOT NULL,
    expires  timestamp with time zone DEFAULT (now() + '24:00:00'::interval) NOT NULL,
    token    text                                                            NOT NULL
);

CREATE TABLE account.sessions
(
    id         uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id    integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE account.password_resets
(
    id         uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id    integer                                                         NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    expires_at timestamp with time zone DEFAULT (now() + '01:00:00'::interval) NOT NULL
);

-- ==========================================
-- 4. AUTH SCHEMA (Security & Access)
-- ==========================================
CREATE TABLE auth.identities
(
    id               uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id          integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    provider         text                                   NOT NULL,
    provider_subject text                                   NOT NULL,
    created_at       timestamp with time zone DEFAULT now() NOT NULL
);

-- ==========================================
-- 5. API SCHEMA (System Keys & Logging)
-- ==========================================
CREATE TABLE api.keys
(
    id                       uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    key_id                   text UNIQUE                                               NOT NULL,
    secret_hash              text                                                      NOT NULL,
    name                     text,
    scopes                   jsonb                    DEFAULT '[]'::jsonb              NOT NULL,
    created_at               timestamp with time zone DEFAULT now()                    NOT NULL,
    last_used_at             timestamp with time zone,
    expires_at               timestamp with time zone,
    status                   api.key_status           DEFAULT 'active'::api.key_status NOT NULL,
    created_by_ip            inet,
    last_used_ip             inet,
    metadata                 jsonb,
    user_id                  integer REFERENCES account.users (id) ON DELETE CASCADE,
    refresh_token_hash       text,
    refresh_token_expires_at timestamp with time zone,
    last_refreshed_at        timestamp with time zone,
    rotated_from_key_id      text
);

CREATE INDEX idx_api_keys_last_used_at ON api.keys USING btree (last_used_at);
CREATE INDEX idx_api_keys_status ON api.keys USING btree (status);

-- ==========================================
-- 6. GQ SCHEMA (Gentry's Quest)
-- ==========================================
CREATE TABLE gq.profiles
(
    account_id integer PRIMARY KEY REFERENCES account.users (id) ON DELETE CASCADE,
    money      bigint   DEFAULT 0                NOT NULL,
    weighted   smallint DEFAULT 0                NOT NULL,
    unweighted integer  DEFAULT 0                NOT NULL,
    rank       text     DEFAULT 'unranked'::text NOT NULL,
    tier       smallint DEFAULT 0                NOT NULL
);

CREATE TABLE gq.items
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metadata jsonb                                 NOT NULL,
    rating   integer                     DEFAULT 0 NOT NULL,
    owner_id integer REFERENCES account.users (id) ON DELETE CASCADE,
    is_new   boolean                     DEFAULT false,
    obtained timestamp without time zone DEFAULT now()
);

CREATE TABLE gq.leaderboards
(
    id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   text    NOT NULL,
    online boolean NOT NULL
);

CREATE TABLE gq.visitations
(
    id       uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id  integer REFERENCES account.users (id) ON DELETE CASCADE,
    location text,
    arrived  timestamp with time zone DEFAULT now() NOT NULL,
    departed timestamp with time zone
);

CREATE TABLE gq.scores
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text                                   NOT NULL,
    score          bigint                                 NOT NULL,
    leaderboard_id integer                                NOT NULL REFERENCES gq.leaderboards (id) ON DELETE CASCADE,
    user_id        integer REFERENCES account.users (id) ON DELETE CASCADE,
    submitted_at   timestamp with time zone DEFAULT now() NOT NULL,
    visitation_id  uuid                                   REFERENCES gq.visitations (id) ON DELETE SET NULL
);

CREATE TABLE gq.statistics
(
    id             uuid                     DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id        integer                                NOT NULL REFERENCES account.users (id) ON DELETE CASCADE,
    type           gq.statistic_type                      NOT NULL,
    amount         integer                  DEFAULT 0     NOT NULL,
    enemy          text                     DEFAULT null,
    character      text                     DEFAULT null,
    weapon         text                     DEFAULT null,
    location       text                     DEFAULT null,
    status_effect  text                     DEFAULT null,
    visitation_id  uuid                                   REFERENCES gq.visitations (id) ON DELETE SET NULL,
    leaderboard_id integer                                REFERENCES gq.leaderboards (id) ON DELETE SET NULL,
    happened       timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX idx_gq_stats_user ON gq.statistics USING btree (user_id);

CREATE TABLE gq.metrics
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer REFERENCES account.users (id) ON DELETE CASCADE,
    recorded_at date    DEFAULT now() NOT NULL,
    rank        integer DEFAULT 0     NOT NULL,
    gp          integer DEFAULT 0     NOT NULL
);

-- ==========================================
-- 7. OSU SCHEMA (Osu! Tracking)
-- ==========================================
create table osu.users
(
    id           bigint                                                                                                                                        not null
        primary key,
    username     text,
    total_score  bigint                   default 0                                                                                                            not null,
    playcount    integer                  default 0                                                                                                            not null,
    accuracy     numeric(5, 2)            default 0                                                                                                            not null,
    pp           integer                  default 0                                                                                                            not null,
    global_rank  integer                  default 0                                                                                                            not null,
    last_refresh timestamp with time zone default now()                                                                                                        not null,
    avatar       text                     default 'https://a.ppy.sh/1'::text                                                                                   not null,
    background   text                     default 'https://c4.wallpaperflare.com/wallpaper/39/35/772/osu-games-art-digital-art-hd-wallpaper-preview.jpg'::text not null,
    country_rank integer                  default 0                                                                                                            not null,
    grade_ss     integer                  default 0                                                                                                            not null,
    grade_ssh    integer                  default 0                                                                                                            not null,
    grade_s      integer                  default 0                                                                                                            not null,
    grade_sh     integer                  default 0                                                                                                            not null,
    grade_a      integer                  default 0                                                                                                            not null,
    ranked_score bigint                   default 0                                                                                                            not null,
    total_hits   integer                  default 0                                                                                                            not null
);

create table osu.matches
(
    id         integer generated by default as identity
        primary key,
    name       text,
    open       boolean                  default true                not null,
    pinned     boolean                  default false               not null,
    ended      boolean                  default false               not null,
    started_at timestamp with time zone default now()               not null,
    opener_id  integer                                              not null
        references account.users
            on delete cascade,
    ended_at   timestamp with time zone,
    objective  text                     default 'total_score'::text not null
);

create table osu.scores
(
    id           bigint                                                                                                                                                                               not null
        constraint scores_pk
            unique,
    submitted_at timestamp with time zone default now()                                                                                                                                               not null,
    beatmap_id   bigint                                                                                                                                                                               not null,
    accuracy     double precision         default 0                                                                                                                                                   not null,
    rank         text                     default 'f'::text                                                                                                                                           not null,
    pp           double precision         default 0,
    score        bigint                   default 0                                                                                                                                                   not null,
    user_id      bigint                                                                                                                                                                               not null
        constraint scores_users_id_fk
            references osu.users
            on update cascade on delete cascade,
    cover        text                     default 'https://i.redd.it/iconic-background-artists-v0-2te23nyjynfe1.png?width=2000&format=png&auto=webp&s=4951f53e40e22c5c430e6be56bab42a1c04df1c1'::text not null,
    title        text                     default 'title'::text                                                                                                                                       not null,
    artist       text                     default 'artist'::text                                                                                                                                      not null
);

create table osu.teams
(
    id       integer    default nextval('osu.match_teams_id_seq'::regclass) not null
        constraint teams_pk
            primary key,
    name     text       default 'team'::text                                not null,
    acronym  varchar(4) default 'team'::character varying                   not null,
    color    varchar(7) default '#808080'::character varying                not null,
    match_id integer
        constraint teams_matches_id_fk
            references osu.matches
            on delete cascade
);

alter sequence osu.match_teams_id_seq owned by osu.teams.id;

create table osu.match_users
(
    match_id         integer                      not null
        references osu.matches
            on delete cascade,
    user_id          bigint                       not null
        references osu.users
            on delete cascade,
    nickname         text,
    team_id          integer
        constraint match_users_teams_id_fk
            references osu.teams
            on update set null on delete set null,
    starting_stats   jsonb    default '{}'::jsonb not null,
    ending_stats     jsonb,
    reconstructed_pp integer  default 0           not null,
    placement        smallint default 0           not null,
    primary key (match_id, user_id)
);

create table osu.match_metrics
(
    match_id  integer               not null
        constraint match_metrics_matches_id_fk
            references osu.matches
            on delete cascade,
    user_id   integer               not null
        constraint match_metrics_users_id_fk
            references osu.users,
    placement integer default 0     not null,
    objective numeric default 0     not null,
    plays     integer default 0     not null,
    date      date    default now() not null,
    constraint match_metrics_pk
        unique (user_id, match_id, date)
);

create function osu.set_match_ended_at() returns trigger
    language plpgsql
as
$$
BEGIN
    IF NEW.ended = TRUE AND (OLD.ended IS FALSE OR OLD.ended IS NULL) THEN
        IF NEW.ended_at IS NULL OR NEW.ended_at = OLD.ended_at THEN
            NEW.ended_at := NOW();
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

create trigger trg_set_match_ended_at
    before update
    on osu.matches
    for each row
    when (new.ended IS TRUE AND (old.ended IS FALSE OR old.ended IS NULL))
execute procedure osu.set_match_ended_at();

