global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gdcheerioscom'
    static_configs:
      - targets: ['gdcheerioscom:8000']

  - job_name: 'gdcheeriosws'
    static_configs:
      - targets: ['gdcheeriosws:8765']
